# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loteria',
            options={'ordering': ['-data']},
        ),
    ]
